"""Add indexes for performance optimization

Revision ID: 4592067c7a74
Revises: a829831525ae
Create Date: 2026-01-09 13:25:16.837645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4592067c7a74'
down_revision = 'a829831525ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_user_active_date', ['user_id', 'is_active', 'payment_date'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_user_date')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index('idx_subscription_user_active_date')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_user_id'))

    # ### end Alembic commands ###
