"""Added checks to the Category and Account models and indexed some columns in the Transaction model for faster queries.

Revision ID: a829831525ae
Revises: ddf6593ec41b
Create Date: 2025-10-10 11:55:51.479994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a829831525ae'
down_revision = 'ddf6593ec41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_account', ['user_id', 'name'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_category', ['user_id', 'name'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_description'))
        batch_op.drop_index(batch_op.f('ix_transaction_category_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_category', type_='unique')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_account', type_='unique')

    # ### end Alembic commands ###
