"""empty message

Revision ID: b3b9f3ffcd15
Revises: f386332a34a8
Create Date: 2025-10-06 11:36:12.192039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b9f3ffcd15'
down_revision = 'f386332a34a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_given_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_given', ['loan_given_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_given_id')

    # ### end Alembic commands ###
