"""The type property was added to the Transaction model along with type validations and relationships with the Debt, LoanGiven, and Subscription models.

Revision ID: cbdb676017c6
Revises: ddb89f195f02
Create Date: 2025-10-08 13:06:51.516380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'cbdb676017c6'
down_revision = 'ddb89f195f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el ENUM type primero
    transaction_type_enum = postgresql.ENUM('general', 'subscription', 'debt_payment', 'loan_payment', name='transactiontype')
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', transaction_type_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    # Eliminar el ENUM type
    transaction_type_enum = postgresql.ENUM('general', 'subscription', 'debt_payment', 'loan_payment', name='transactiontype')
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
