"""The Debt model was created along with its relationships with the User and Transaction models.

Revision ID: de3b86b415bd
Revises: bbe1c52bfd0b
Create Date: 2025-10-01 12:38:19.977237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b86b415bd'
down_revision = 'bbe1c52bfd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creditor', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('remaining_amount', sa.Float(), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'debt', ['debt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('debt_id')

    op.drop_table('debt')
    # ### end Alembic commands ###
