"""The LoanGiven model was created along with its relationships to the User, Transaction and Installment models.

Revision ID: f386332a34a8
Revises: a19716927261
Create Date: 2025-10-06 11:23:26.781764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f386332a34a8'
down_revision = 'a19716927261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_given',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debtor', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'overdue', name='statustype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_given_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_given', ['loan_given_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_given_id')

    op.drop_table('loan_given')
    # ### end Alembic commands ###
