"""The Installment model was created along with its relationships with the Debt and Transaction models.

Revision ID: f3ff1e14bfe5
Revises: de3b86b415bd
Create Date: 2025-10-01 13:25:16.248733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3ff1e14bfe5'
down_revision = 'de3b86b415bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Usar el enum existente en lugar de crear uno nuevo
    statustype_enum = postgresql.ENUM('pending', 'paid', 'overdue', name='statustype', create_type=False)
    
    op.create_table('installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', statustype_enum, nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installment')
    # ### end Alembic commands ###
