"""The Report model was created along with its relationship with the User model.

Revision ID: f62013aa2ef0
Revises: 3dcdadbe38f9
Create Date: 2025-10-07 12:06:59.209911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62013aa2ef0'
down_revision = '3dcdadbe38f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('type', sa.Enum('weekly', 'monthly', 'yearly', name='reporttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
